# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcelo-origoni/Documents/taller/grupal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcelo-origoni/Documents/taller/grupal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo-origoni/Documents/taller/grupal/CMakeFiles /home/marcelo-origoni/Documents/taller/grupal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo-origoni/Documents/taller/grupal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_client

# Build rule for target.
taller_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client
.PHONY : taller_client

# fast build rule for target.
taller_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/build
.PHONY : taller_client/fast

#=============================================================================
# Target rules for targets named taller_server

# Build rule for target.
taller_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_server
.PHONY : taller_server

# fast build rule for target.
taller_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/build
.PHONY : taller_server/fast

#=============================================================================
# Target rules for targets named taller_editor

# Build rule for target.
taller_editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor
.PHONY : taller_editor

# fast build rule for target.
taller_editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/build
.PHONY : taller_editor/fast

#=============================================================================
# Target rules for targets named taller_tests

# Build rule for target.
taller_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_tests
.PHONY : taller_tests

# fast build rule for target.
taller_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/build
.PHONY : taller_tests/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

client/clientprotocol.o: client/clientprotocol.cpp.o
.PHONY : client/clientprotocol.o

# target to build an object file
client/clientprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/clientprotocol.cpp.o
.PHONY : client/clientprotocol.cpp.o

client/clientprotocol.i: client/clientprotocol.cpp.i
.PHONY : client/clientprotocol.i

# target to preprocess a source file
client/clientprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/clientprotocol.cpp.i
.PHONY : client/clientprotocol.cpp.i

client/clientprotocol.s: client/clientprotocol.cpp.s
.PHONY : client/clientprotocol.s

# target to generate assembly for a file
client/clientprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/clientprotocol.cpp.s
.PHONY : client/clientprotocol.cpp.s

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/protocol.o: common/protocol.cpp.o
.PHONY : common/protocol.o

# target to build an object file
common/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.o
.PHONY : common/protocol.cpp.o

common/protocol.i: common/protocol.cpp.i
.PHONY : common/protocol.i

# target to preprocess a source file
common/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.i
.PHONY : common/protocol.cpp.i

common/protocol.s: common/protocol.cpp.s
.PHONY : common/protocol.s

# target to generate assembly for a file
common/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocol.cpp.s
.PHONY : common/protocol.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

editor/main.o: editor/main.cpp.o
.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i
.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s
.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

server/controlledplayer.o: server/controlledplayer.cpp.o
.PHONY : server/controlledplayer.o

# target to build an object file
server/controlledplayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.o
.PHONY : server/controlledplayer.cpp.o

server/controlledplayer.i: server/controlledplayer.cpp.i
.PHONY : server/controlledplayer.i

# target to preprocess a source file
server/controlledplayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.i
.PHONY : server/controlledplayer.cpp.i

server/controlledplayer.s: server/controlledplayer.cpp.s
.PHONY : server/controlledplayer.s

# target to generate assembly for a file
server/controlledplayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.s
.PHONY : server/controlledplayer.cpp.s

server/controlnotifier.o: server/controlnotifier.cpp.o
.PHONY : server/controlnotifier.o

# target to build an object file
server/controlnotifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.o
.PHONY : server/controlnotifier.cpp.o

server/controlnotifier.i: server/controlnotifier.cpp.i
.PHONY : server/controlnotifier.i

# target to preprocess a source file
server/controlnotifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.i
.PHONY : server/controlnotifier.cpp.i

server/controlnotifier.s: server/controlnotifier.cpp.s
.PHONY : server/controlnotifier.s

# target to generate assembly for a file
server/controlnotifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.s
.PHONY : server/controlnotifier.cpp.s

server/controlreceiver.o: server/controlreceiver.cpp.o
.PHONY : server/controlreceiver.o

# target to build an object file
server/controlreceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.o
.PHONY : server/controlreceiver.cpp.o

server/controlreceiver.i: server/controlreceiver.cpp.i
.PHONY : server/controlreceiver.i

# target to preprocess a source file
server/controlreceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.i
.PHONY : server/controlreceiver.cpp.i

server/controlreceiver.s: server/controlreceiver.cpp.s
.PHONY : server/controlreceiver.s

# target to generate assembly for a file
server/controlreceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.s
.PHONY : server/controlreceiver.cpp.s

server/gameerror.o: server/gameerror.cpp.o
.PHONY : server/gameerror.o

# target to build an object file
server/gameerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.o
.PHONY : server/gameerror.cpp.o

server/gameerror.i: server/gameerror.cpp.i
.PHONY : server/gameerror.i

# target to preprocess a source file
server/gameerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.i
.PHONY : server/gameerror.cpp.i

server/gameerror.s: server/gameerror.cpp.s
.PHONY : server/gameerror.s

# target to generate assembly for a file
server/gameerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.s
.PHONY : server/gameerror.cpp.s

server/lobbycontainer.o: server/lobbycontainer.cpp.o
.PHONY : server/lobbycontainer.o

# target to build an object file
server/lobbycontainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.o
.PHONY : server/lobbycontainer.cpp.o

server/lobbycontainer.i: server/lobbycontainer.cpp.i
.PHONY : server/lobbycontainer.i

# target to preprocess a source file
server/lobbycontainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.i
.PHONY : server/lobbycontainer.cpp.i

server/lobbycontainer.s: server/lobbycontainer.cpp.s
.PHONY : server/lobbycontainer.s

# target to generate assembly for a file
server/lobbycontainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.s
.PHONY : server/lobbycontainer.cpp.s

server/logic_server/action.o: server/logic_server/action.cpp.o
.PHONY : server/logic_server/action.o

# target to build an object file
server/logic_server/action.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/action.cpp.o
.PHONY : server/logic_server/action.cpp.o

server/logic_server/action.i: server/logic_server/action.cpp.i
.PHONY : server/logic_server/action.i

# target to preprocess a source file
server/logic_server/action.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/action.cpp.i
.PHONY : server/logic_server/action.cpp.i

server/logic_server/action.s: server/logic_server/action.cpp.s
.PHONY : server/logic_server/action.s

# target to generate assembly for a file
server/logic_server/action.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/action.cpp.s
.PHONY : server/logic_server/action.cpp.s

server/logic_server/armor.o: server/logic_server/armor.cpp.o
.PHONY : server/logic_server/armor.o

# target to build an object file
server/logic_server/armor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/armor.cpp.o
.PHONY : server/logic_server/armor.cpp.o

server/logic_server/armor.i: server/logic_server/armor.cpp.i
.PHONY : server/logic_server/armor.i

# target to preprocess a source file
server/logic_server/armor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/armor.cpp.i
.PHONY : server/logic_server/armor.cpp.i

server/logic_server/armor.s: server/logic_server/armor.cpp.s
.PHONY : server/logic_server/armor.s

# target to generate assembly for a file
server/logic_server/armor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/armor.cpp.s
.PHONY : server/logic_server/armor.cpp.s

server/logic_server/box.o: server/logic_server/box.cpp.o
.PHONY : server/logic_server/box.o

# target to build an object file
server/logic_server/box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/box.cpp.o
.PHONY : server/logic_server/box.cpp.o

server/logic_server/box.i: server/logic_server/box.cpp.i
.PHONY : server/logic_server/box.i

# target to preprocess a source file
server/logic_server/box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/box.cpp.i
.PHONY : server/logic_server/box.cpp.i

server/logic_server/box.s: server/logic_server/box.cpp.s
.PHONY : server/logic_server/box.s

# target to generate assembly for a file
server/logic_server/box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/box.cpp.s
.PHONY : server/logic_server/box.cpp.s

server/logic_server/coordinates.o: server/logic_server/coordinates.cpp.o
.PHONY : server/logic_server/coordinates.o

# target to build an object file
server/logic_server/coordinates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/coordinates.cpp.o
.PHONY : server/logic_server/coordinates.cpp.o

server/logic_server/coordinates.i: server/logic_server/coordinates.cpp.i
.PHONY : server/logic_server/coordinates.i

# target to preprocess a source file
server/logic_server/coordinates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/coordinates.cpp.i
.PHONY : server/logic_server/coordinates.cpp.i

server/logic_server/coordinates.s: server/logic_server/coordinates.cpp.s
.PHONY : server/logic_server/coordinates.s

# target to generate assembly for a file
server/logic_server/coordinates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/coordinates.cpp.s
.PHONY : server/logic_server/coordinates.cpp.s

server/logic_server/match_logic.o: server/logic_server/match_logic.cpp.o
.PHONY : server/logic_server/match_logic.o

# target to build an object file
server/logic_server/match_logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_logic.cpp.o
.PHONY : server/logic_server/match_logic.cpp.o

server/logic_server/match_logic.i: server/logic_server/match_logic.cpp.i
.PHONY : server/logic_server/match_logic.i

# target to preprocess a source file
server/logic_server/match_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_logic.cpp.i
.PHONY : server/logic_server/match_logic.cpp.i

server/logic_server/match_logic.s: server/logic_server/match_logic.cpp.s
.PHONY : server/logic_server/match_logic.s

# target to generate assembly for a file
server/logic_server/match_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_logic.cpp.s
.PHONY : server/logic_server/match_logic.cpp.s

server/logic_server/match_queue.o: server/logic_server/match_queue.cpp.o
.PHONY : server/logic_server/match_queue.o

# target to build an object file
server/logic_server/match_queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_queue.cpp.o
.PHONY : server/logic_server/match_queue.cpp.o

server/logic_server/match_queue.i: server/logic_server/match_queue.cpp.i
.PHONY : server/logic_server/match_queue.i

# target to preprocess a source file
server/logic_server/match_queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_queue.cpp.i
.PHONY : server/logic_server/match_queue.cpp.i

server/logic_server/match_queue.s: server/logic_server/match_queue.cpp.s
.PHONY : server/logic_server/match_queue.s

# target to generate assembly for a file
server/logic_server/match_queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_queue.cpp.s
.PHONY : server/logic_server/match_queue.cpp.s

server/logic_server/match_state.o: server/logic_server/match_state.cpp.o
.PHONY : server/logic_server/match_state.o

# target to build an object file
server/logic_server/match_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_state.cpp.o
.PHONY : server/logic_server/match_state.cpp.o

server/logic_server/match_state.i: server/logic_server/match_state.cpp.i
.PHONY : server/logic_server/match_state.i

# target to preprocess a source file
server/logic_server/match_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_state.cpp.i
.PHONY : server/logic_server/match_state.cpp.i

server/logic_server/match_state.s: server/logic_server/match_state.cpp.s
.PHONY : server/logic_server/match_state.s

# target to generate assembly for a file
server/logic_server/match_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/match_state.cpp.s
.PHONY : server/logic_server/match_state.cpp.s

server/logic_server/player.o: server/logic_server/player.cpp.o
.PHONY : server/logic_server/player.o

# target to build an object file
server/logic_server/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/player.cpp.o
.PHONY : server/logic_server/player.cpp.o

server/logic_server/player.i: server/logic_server/player.cpp.i
.PHONY : server/logic_server/player.i

# target to preprocess a source file
server/logic_server/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/player.cpp.i
.PHONY : server/logic_server/player.cpp.i

server/logic_server/player.s: server/logic_server/player.cpp.s
.PHONY : server/logic_server/player.s

# target to generate assembly for a file
server/logic_server/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/player.cpp.s
.PHONY : server/logic_server/player.cpp.s

server/logic_server/weapon.o: server/logic_server/weapon.cpp.o
.PHONY : server/logic_server/weapon.o

# target to build an object file
server/logic_server/weapon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/weapon.cpp.o
.PHONY : server/logic_server/weapon.cpp.o

server/logic_server/weapon.i: server/logic_server/weapon.cpp.i
.PHONY : server/logic_server/weapon.i

# target to preprocess a source file
server/logic_server/weapon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/weapon.cpp.i
.PHONY : server/logic_server/weapon.cpp.i

server/logic_server/weapon.s: server/logic_server/weapon.cpp.s
.PHONY : server/logic_server/weapon.s

# target to generate assembly for a file
server/logic_server/weapon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/logic_server/weapon.cpp.s
.PHONY : server/logic_server/weapon.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/match.o: server/match.cpp.o
.PHONY : server/match.o

# target to build an object file
server/match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.o
.PHONY : server/match.cpp.o

server/match.i: server/match.cpp.i
.PHONY : server/match.i

# target to preprocess a source file
server/match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.i
.PHONY : server/match.cpp.i

server/match.s: server/match.cpp.s
.PHONY : server/match.s

# target to generate assembly for a file
server/match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.s
.PHONY : server/match.cpp.s

server/playeracceptor.o: server/playeracceptor.cpp.o
.PHONY : server/playeracceptor.o

# target to build an object file
server/playeracceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.o
.PHONY : server/playeracceptor.cpp.o

server/playeracceptor.i: server/playeracceptor.cpp.i
.PHONY : server/playeracceptor.i

# target to preprocess a source file
server/playeracceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.i
.PHONY : server/playeracceptor.cpp.i

server/playeracceptor.s: server/playeracceptor.cpp.s
.PHONY : server/playeracceptor.s

# target to generate assembly for a file
server/playeracceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.s
.PHONY : server/playeracceptor.cpp.s

server/playercontainer.o: server/playercontainer.cpp.o
.PHONY : server/playercontainer.o

# target to build an object file
server/playercontainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.o
.PHONY : server/playercontainer.cpp.o

server/playercontainer.i: server/playercontainer.cpp.i
.PHONY : server/playercontainer.i

# target to preprocess a source file
server/playercontainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.i
.PHONY : server/playercontainer.cpp.i

server/playercontainer.s: server/playercontainer.cpp.s
.PHONY : server/playercontainer.s

# target to generate assembly for a file
server/playercontainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.s
.PHONY : server/playercontainer.cpp.s

server/playerprotocol.o: server/playerprotocol.cpp.o
.PHONY : server/playerprotocol.o

# target to build an object file
server/playerprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playerprotocol.cpp.o
.PHONY : server/playerprotocol.cpp.o

server/playerprotocol.i: server/playerprotocol.cpp.i
.PHONY : server/playerprotocol.i

# target to preprocess a source file
server/playerprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playerprotocol.cpp.i
.PHONY : server/playerprotocol.cpp.i

server/playerprotocol.s: server/playerprotocol.cpp.s
.PHONY : server/playerprotocol.s

# target to generate assembly for a file
server/playerprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playerprotocol.cpp.s
.PHONY : server/playerprotocol.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

server/simple_logic/simpleaction.o: server/simple_logic/simpleaction.cpp.o
.PHONY : server/simple_logic/simpleaction.o

# target to build an object file
server/simple_logic/simpleaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.o
.PHONY : server/simple_logic/simpleaction.cpp.o

server/simple_logic/simpleaction.i: server/simple_logic/simpleaction.cpp.i
.PHONY : server/simple_logic/simpleaction.i

# target to preprocess a source file
server/simple_logic/simpleaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.i
.PHONY : server/simple_logic/simpleaction.cpp.i

server/simple_logic/simpleaction.s: server/simple_logic/simpleaction.cpp.s
.PHONY : server/simple_logic/simpleaction.s

# target to generate assembly for a file
server/simple_logic/simpleaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.s
.PHONY : server/simple_logic/simpleaction.cpp.s

server/simple_logic/simplebox.o: server/simple_logic/simplebox.cpp.o
.PHONY : server/simple_logic/simplebox.o

# target to build an object file
server/simple_logic/simplebox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.o
.PHONY : server/simple_logic/simplebox.cpp.o

server/simple_logic/simplebox.i: server/simple_logic/simplebox.cpp.i
.PHONY : server/simple_logic/simplebox.i

# target to preprocess a source file
server/simple_logic/simplebox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.i
.PHONY : server/simple_logic/simplebox.cpp.i

server/simple_logic/simplebox.s: server/simple_logic/simplebox.cpp.s
.PHONY : server/simple_logic/simplebox.s

# target to generate assembly for a file
server/simple_logic/simplebox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.s
.PHONY : server/simple_logic/simplebox.cpp.s

server/simple_logic/simpleloop.o: server/simple_logic/simpleloop.cpp.o
.PHONY : server/simple_logic/simpleloop.o

# target to build an object file
server/simple_logic/simpleloop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.o
.PHONY : server/simple_logic/simpleloop.cpp.o

server/simple_logic/simpleloop.i: server/simple_logic/simpleloop.cpp.i
.PHONY : server/simple_logic/simpleloop.i

# target to preprocess a source file
server/simple_logic/simpleloop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.i
.PHONY : server/simple_logic/simpleloop.cpp.i

server/simple_logic/simpleloop.s: server/simple_logic/simpleloop.cpp.s
.PHONY : server/simple_logic/simpleloop.s

# target to generate assembly for a file
server/simple_logic/simpleloop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.s
.PHONY : server/simple_logic/simpleloop.cpp.s

server/simple_logic/simplequeue.o: server/simple_logic/simplequeue.cpp.o
.PHONY : server/simple_logic/simplequeue.o

# target to build an object file
server/simple_logic/simplequeue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.o
.PHONY : server/simple_logic/simplequeue.cpp.o

server/simple_logic/simplequeue.i: server/simple_logic/simplequeue.cpp.i
.PHONY : server/simple_logic/simplequeue.i

# target to preprocess a source file
server/simple_logic/simplequeue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.i
.PHONY : server/simple_logic/simplequeue.cpp.i

server/simple_logic/simplequeue.s: server/simple_logic/simplequeue.cpp.s
.PHONY : server/simple_logic/simplequeue.s

# target to generate assembly for a file
server/simple_logic/simplequeue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.s
.PHONY : server/simple_logic/simplequeue.cpp.s

server/simple_logic/simplereward.o: server/simple_logic/simplereward.cpp.o
.PHONY : server/simple_logic/simplereward.o

# target to build an object file
server/simple_logic/simplereward.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.o
.PHONY : server/simple_logic/simplereward.cpp.o

server/simple_logic/simplereward.i: server/simple_logic/simplereward.cpp.i
.PHONY : server/simple_logic/simplereward.i

# target to preprocess a source file
server/simple_logic/simplereward.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.i
.PHONY : server/simple_logic/simplereward.cpp.i

server/simple_logic/simplereward.s: server/simple_logic/simplereward.cpp.s
.PHONY : server/simple_logic/simplereward.s

# target to generate assembly for a file
server/simple_logic/simplereward.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.s
.PHONY : server/simple_logic/simplereward.cpp.s

server/simple_logic/simplestate.o: server/simple_logic/simplestate.cpp.o
.PHONY : server/simple_logic/simplestate.o

# target to build an object file
server/simple_logic/simplestate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.o
.PHONY : server/simple_logic/simplestate.cpp.o

server/simple_logic/simplestate.i: server/simple_logic/simplestate.cpp.i
.PHONY : server/simple_logic/simplestate.i

# target to preprocess a source file
server/simple_logic/simplestate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.i
.PHONY : server/simple_logic/simplestate.cpp.i

server/simple_logic/simplestate.s: server/simple_logic/simplestate.cpp.s
.PHONY : server/simple_logic/simplestate.s

# target to generate assembly for a file
server/simple_logic/simplestate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.s
.PHONY : server/simple_logic/simplestate.cpp.s

tests/foo.o: tests/foo.cpp.o
.PHONY : tests/foo.o

# target to build an object file
tests/foo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/foo.cpp.o
.PHONY : tests/foo.cpp.o

tests/foo.i: tests/foo.cpp.i
.PHONY : tests/foo.i

# target to preprocess a source file
tests/foo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/foo.cpp.i
.PHONY : tests/foo.cpp.i

tests/foo.s: tests/foo.cpp.s
.PHONY : tests/foo.s

# target to generate assembly for a file
tests/foo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/foo.cpp.s
.PHONY : tests/foo.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SDL2pp"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... taller_client"
	@echo "... taller_common"
	@echo "... taller_editor"
	@echo "... taller_server"
	@echo "... taller_tests"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/clientprotocol.o"
	@echo "... client/clientprotocol.i"
	@echo "... client/clientprotocol.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/protocol.o"
	@echo "... common/protocol.i"
	@echo "... common/protocol.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... server/controlledplayer.o"
	@echo "... server/controlledplayer.i"
	@echo "... server/controlledplayer.s"
	@echo "... server/controlnotifier.o"
	@echo "... server/controlnotifier.i"
	@echo "... server/controlnotifier.s"
	@echo "... server/controlreceiver.o"
	@echo "... server/controlreceiver.i"
	@echo "... server/controlreceiver.s"
	@echo "... server/gameerror.o"
	@echo "... server/gameerror.i"
	@echo "... server/gameerror.s"
	@echo "... server/lobbycontainer.o"
	@echo "... server/lobbycontainer.i"
	@echo "... server/lobbycontainer.s"
	@echo "... server/logic_server/action.o"
	@echo "... server/logic_server/action.i"
	@echo "... server/logic_server/action.s"
	@echo "... server/logic_server/armor.o"
	@echo "... server/logic_server/armor.i"
	@echo "... server/logic_server/armor.s"
	@echo "... server/logic_server/box.o"
	@echo "... server/logic_server/box.i"
	@echo "... server/logic_server/box.s"
	@echo "... server/logic_server/coordinates.o"
	@echo "... server/logic_server/coordinates.i"
	@echo "... server/logic_server/coordinates.s"
	@echo "... server/logic_server/match_logic.o"
	@echo "... server/logic_server/match_logic.i"
	@echo "... server/logic_server/match_logic.s"
	@echo "... server/logic_server/match_queue.o"
	@echo "... server/logic_server/match_queue.i"
	@echo "... server/logic_server/match_queue.s"
	@echo "... server/logic_server/match_state.o"
	@echo "... server/logic_server/match_state.i"
	@echo "... server/logic_server/match_state.s"
	@echo "... server/logic_server/player.o"
	@echo "... server/logic_server/player.i"
	@echo "... server/logic_server/player.s"
	@echo "... server/logic_server/weapon.o"
	@echo "... server/logic_server/weapon.i"
	@echo "... server/logic_server/weapon.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/match.o"
	@echo "... server/match.i"
	@echo "... server/match.s"
	@echo "... server/playeracceptor.o"
	@echo "... server/playeracceptor.i"
	@echo "... server/playeracceptor.s"
	@echo "... server/playercontainer.o"
	@echo "... server/playercontainer.i"
	@echo "... server/playercontainer.s"
	@echo "... server/playerprotocol.o"
	@echo "... server/playerprotocol.i"
	@echo "... server/playerprotocol.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... server/simple_logic/simpleaction.o"
	@echo "... server/simple_logic/simpleaction.i"
	@echo "... server/simple_logic/simpleaction.s"
	@echo "... server/simple_logic/simplebox.o"
	@echo "... server/simple_logic/simplebox.i"
	@echo "... server/simple_logic/simplebox.s"
	@echo "... server/simple_logic/simpleloop.o"
	@echo "... server/simple_logic/simpleloop.i"
	@echo "... server/simple_logic/simpleloop.s"
	@echo "... server/simple_logic/simplequeue.o"
	@echo "... server/simple_logic/simplequeue.i"
	@echo "... server/simple_logic/simplequeue.s"
	@echo "... server/simple_logic/simplereward.o"
	@echo "... server/simple_logic/simplereward.i"
	@echo "... server/simple_logic/simplereward.s"
	@echo "... server/simple_logic/simplestate.o"
	@echo "... server/simple_logic/simplestate.i"
	@echo "... server/simple_logic/simplestate.s"
	@echo "... tests/foo.o"
	@echo "... tests/foo.i"
	@echo "... tests/foo.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

