# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcelo-origoni/Documents/taller/grupal

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcelo-origoni/Documents/taller/grupal

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo-origoni/Documents/taller/grupal/CMakeFiles /home/marcelo-origoni/Documents/taller/grupal//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcelo-origoni/Documents/taller/grupal/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_client

# Build rule for target.
taller_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client
.PHONY : taller_client

# fast build rule for target.
taller_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/build
.PHONY : taller_client/fast

#=============================================================================
# Target rules for targets named taller_server

# Build rule for target.
taller_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_server
.PHONY : taller_server

# fast build rule for target.
taller_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/build
.PHONY : taller_server/fast

#=============================================================================
# Target rules for targets named taller_editor

# Build rule for target.
taller_editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor
.PHONY : taller_editor

# fast build rule for target.
taller_editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/build
.PHONY : taller_editor/fast

#=============================================================================
# Target rules for targets named taller_tests

# Build rule for target.
taller_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_tests
.PHONY : taller_tests

# fast build rule for target.
taller_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/build
.PHONY : taller_tests/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

common/clientprotocol.o: common/clientprotocol.cpp.o
.PHONY : common/clientprotocol.o

# target to build an object file
common/clientprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/clientprotocol.cpp.o
.PHONY : common/clientprotocol.cpp.o

common/clientprotocol.i: common/clientprotocol.cpp.i
.PHONY : common/clientprotocol.i

# target to preprocess a source file
common/clientprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/clientprotocol.cpp.i
.PHONY : common/clientprotocol.cpp.i

common/clientprotocol.s: common/clientprotocol.cpp.s
.PHONY : common/clientprotocol.s

# target to generate assembly for a file
common/clientprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/clientprotocol.cpp.s
.PHONY : common/clientprotocol.cpp.s

common/core/liberror.o: common/core/liberror.cpp.o
.PHONY : common/core/liberror.o

# target to build an object file
common/core/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/liberror.cpp.o
.PHONY : common/core/liberror.cpp.o

common/core/liberror.i: common/core/liberror.cpp.i
.PHONY : common/core/liberror.i

# target to preprocess a source file
common/core/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/liberror.cpp.i
.PHONY : common/core/liberror.cpp.i

common/core/liberror.s: common/core/liberror.cpp.s
.PHONY : common/core/liberror.s

# target to generate assembly for a file
common/core/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/liberror.cpp.s
.PHONY : common/core/liberror.cpp.s

common/core/protocol.o: common/core/protocol.cpp.o
.PHONY : common/core/protocol.o

# target to build an object file
common/core/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/protocol.cpp.o
.PHONY : common/core/protocol.cpp.o

common/core/protocol.i: common/core/protocol.cpp.i
.PHONY : common/core/protocol.i

# target to preprocess a source file
common/core/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/protocol.cpp.i
.PHONY : common/core/protocol.cpp.i

common/core/protocol.s: common/core/protocol.cpp.s
.PHONY : common/core/protocol.s

# target to generate assembly for a file
common/core/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/protocol.cpp.s
.PHONY : common/core/protocol.cpp.s

common/core/resolver.o: common/core/resolver.cpp.o
.PHONY : common/core/resolver.o

# target to build an object file
common/core/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolver.cpp.o
.PHONY : common/core/resolver.cpp.o

common/core/resolver.i: common/core/resolver.cpp.i
.PHONY : common/core/resolver.i

# target to preprocess a source file
common/core/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolver.cpp.i
.PHONY : common/core/resolver.cpp.i

common/core/resolver.s: common/core/resolver.cpp.s
.PHONY : common/core/resolver.s

# target to generate assembly for a file
common/core/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolver.cpp.s
.PHONY : common/core/resolver.cpp.s

common/core/resolvererror.o: common/core/resolvererror.cpp.o
.PHONY : common/core/resolvererror.o

# target to build an object file
common/core/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolvererror.cpp.o
.PHONY : common/core/resolvererror.cpp.o

common/core/resolvererror.i: common/core/resolvererror.cpp.i
.PHONY : common/core/resolvererror.i

# target to preprocess a source file
common/core/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolvererror.cpp.i
.PHONY : common/core/resolvererror.cpp.i

common/core/resolvererror.s: common/core/resolvererror.cpp.s
.PHONY : common/core/resolvererror.s

# target to generate assembly for a file
common/core/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/resolvererror.cpp.s
.PHONY : common/core/resolvererror.cpp.s

common/core/socket.o: common/core/socket.cpp.o
.PHONY : common/core/socket.o

# target to build an object file
common/core/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/socket.cpp.o
.PHONY : common/core/socket.cpp.o

common/core/socket.i: common/core/socket.cpp.i
.PHONY : common/core/socket.i

# target to preprocess a source file
common/core/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/socket.cpp.i
.PHONY : common/core/socket.cpp.i

common/core/socket.s: common/core/socket.cpp.s
.PHONY : common/core/socket.s

# target to generate assembly for a file
common/core/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/core/socket.cpp.s
.PHONY : common/core/socket.cpp.s

common/protocolerror.o: common/protocolerror.cpp.o
.PHONY : common/protocolerror.o

# target to build an object file
common/protocolerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocolerror.cpp.o
.PHONY : common/protocolerror.cpp.o

common/protocolerror.i: common/protocolerror.cpp.i
.PHONY : common/protocolerror.i

# target to preprocess a source file
common/protocolerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocolerror.cpp.i
.PHONY : common/protocolerror.cpp.i

common/protocolerror.s: common/protocolerror.cpp.s
.PHONY : common/protocolerror.s

# target to generate assembly for a file
common/protocolerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/protocolerror.cpp.s
.PHONY : common/protocolerror.cpp.s

common/serverprotocol.o: common/serverprotocol.cpp.o
.PHONY : common/serverprotocol.o

# target to build an object file
common/serverprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/serverprotocol.cpp.o
.PHONY : common/serverprotocol.cpp.o

common/serverprotocol.i: common/serverprotocol.cpp.i
.PHONY : common/serverprotocol.i

# target to preprocess a source file
common/serverprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/serverprotocol.cpp.i
.PHONY : common/serverprotocol.cpp.i

common/serverprotocol.s: common/serverprotocol.cpp.s
.PHONY : common/serverprotocol.s

# target to generate assembly for a file
common/serverprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/serverprotocol.cpp.s
.PHONY : common/serverprotocol.cpp.s

editor/main.o: editor/main.cpp.o
.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i
.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s
.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

server/controlledplayer.o: server/controlledplayer.cpp.o
.PHONY : server/controlledplayer.o

# target to build an object file
server/controlledplayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.o
.PHONY : server/controlledplayer.cpp.o

server/controlledplayer.i: server/controlledplayer.cpp.i
.PHONY : server/controlledplayer.i

# target to preprocess a source file
server/controlledplayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.i
.PHONY : server/controlledplayer.cpp.i

server/controlledplayer.s: server/controlledplayer.cpp.s
.PHONY : server/controlledplayer.s

# target to generate assembly for a file
server/controlledplayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlledplayer.cpp.s
.PHONY : server/controlledplayer.cpp.s

server/controlnotifier.o: server/controlnotifier.cpp.o
.PHONY : server/controlnotifier.o

# target to build an object file
server/controlnotifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.o
.PHONY : server/controlnotifier.cpp.o

server/controlnotifier.i: server/controlnotifier.cpp.i
.PHONY : server/controlnotifier.i

# target to preprocess a source file
server/controlnotifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.i
.PHONY : server/controlnotifier.cpp.i

server/controlnotifier.s: server/controlnotifier.cpp.s
.PHONY : server/controlnotifier.s

# target to generate assembly for a file
server/controlnotifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlnotifier.cpp.s
.PHONY : server/controlnotifier.cpp.s

server/controlreceiver.o: server/controlreceiver.cpp.o
.PHONY : server/controlreceiver.o

# target to build an object file
server/controlreceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.o
.PHONY : server/controlreceiver.cpp.o

server/controlreceiver.i: server/controlreceiver.cpp.i
.PHONY : server/controlreceiver.i

# target to preprocess a source file
server/controlreceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.i
.PHONY : server/controlreceiver.cpp.i

server/controlreceiver.s: server/controlreceiver.cpp.s
.PHONY : server/controlreceiver.s

# target to generate assembly for a file
server/controlreceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/controlreceiver.cpp.s
.PHONY : server/controlreceiver.cpp.s

server/gameerror.o: server/gameerror.cpp.o
.PHONY : server/gameerror.o

# target to build an object file
server/gameerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.o
.PHONY : server/gameerror.cpp.o

server/gameerror.i: server/gameerror.cpp.i
.PHONY : server/gameerror.i

# target to preprocess a source file
server/gameerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.i
.PHONY : server/gameerror.cpp.i

server/gameerror.s: server/gameerror.cpp.s
.PHONY : server/gameerror.s

# target to generate assembly for a file
server/gameerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameerror.cpp.s
.PHONY : server/gameerror.cpp.s

server/lobbycontainer.o: server/lobbycontainer.cpp.o
.PHONY : server/lobbycontainer.o

# target to build an object file
server/lobbycontainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.o
.PHONY : server/lobbycontainer.cpp.o

server/lobbycontainer.i: server/lobbycontainer.cpp.i
.PHONY : server/lobbycontainer.i

# target to preprocess a source file
server/lobbycontainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.i
.PHONY : server/lobbycontainer.cpp.i

server/lobbycontainer.s: server/lobbycontainer.cpp.s
.PHONY : server/lobbycontainer.s

# target to generate assembly for a file
server/lobbycontainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/lobbycontainer.cpp.s
.PHONY : server/lobbycontainer.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

server/match.o: server/match.cpp.o
.PHONY : server/match.o

# target to build an object file
server/match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.o
.PHONY : server/match.cpp.o

server/match.i: server/match.cpp.i
.PHONY : server/match.i

# target to preprocess a source file
server/match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.i
.PHONY : server/match.cpp.i

server/match.s: server/match.cpp.s
.PHONY : server/match.s

# target to generate assembly for a file
server/match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.s
.PHONY : server/match.cpp.s

server/playeracceptor.o: server/playeracceptor.cpp.o
.PHONY : server/playeracceptor.o

# target to build an object file
server/playeracceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.o
.PHONY : server/playeracceptor.cpp.o

server/playeracceptor.i: server/playeracceptor.cpp.i
.PHONY : server/playeracceptor.i

# target to preprocess a source file
server/playeracceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.i
.PHONY : server/playeracceptor.cpp.i

server/playeracceptor.s: server/playeracceptor.cpp.s
.PHONY : server/playeracceptor.s

# target to generate assembly for a file
server/playeracceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playeracceptor.cpp.s
.PHONY : server/playeracceptor.cpp.s

server/playercontainer.o: server/playercontainer.cpp.o
.PHONY : server/playercontainer.o

# target to build an object file
server/playercontainer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.o
.PHONY : server/playercontainer.cpp.o

server/playercontainer.i: server/playercontainer.cpp.i
.PHONY : server/playercontainer.i

# target to preprocess a source file
server/playercontainer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.i
.PHONY : server/playercontainer.cpp.i

server/playercontainer.s: server/playercontainer.cpp.s
.PHONY : server/playercontainer.s

# target to generate assembly for a file
server/playercontainer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/playercontainer.cpp.s
.PHONY : server/playercontainer.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

server/simple_logic/simpleaction.o: server/simple_logic/simpleaction.cpp.o
.PHONY : server/simple_logic/simpleaction.o

# target to build an object file
server/simple_logic/simpleaction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.o
.PHONY : server/simple_logic/simpleaction.cpp.o

server/simple_logic/simpleaction.i: server/simple_logic/simpleaction.cpp.i
.PHONY : server/simple_logic/simpleaction.i

# target to preprocess a source file
server/simple_logic/simpleaction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.i
.PHONY : server/simple_logic/simpleaction.cpp.i

server/simple_logic/simpleaction.s: server/simple_logic/simpleaction.cpp.s
.PHONY : server/simple_logic/simpleaction.s

# target to generate assembly for a file
server/simple_logic/simpleaction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleaction.cpp.s
.PHONY : server/simple_logic/simpleaction.cpp.s

server/simple_logic/simplebox.o: server/simple_logic/simplebox.cpp.o
.PHONY : server/simple_logic/simplebox.o

# target to build an object file
server/simple_logic/simplebox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.o
.PHONY : server/simple_logic/simplebox.cpp.o

server/simple_logic/simplebox.i: server/simple_logic/simplebox.cpp.i
.PHONY : server/simple_logic/simplebox.i

# target to preprocess a source file
server/simple_logic/simplebox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.i
.PHONY : server/simple_logic/simplebox.cpp.i

server/simple_logic/simplebox.s: server/simple_logic/simplebox.cpp.s
.PHONY : server/simple_logic/simplebox.s

# target to generate assembly for a file
server/simple_logic/simplebox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplebox.cpp.s
.PHONY : server/simple_logic/simplebox.cpp.s

server/simple_logic/simpleloop.o: server/simple_logic/simpleloop.cpp.o
.PHONY : server/simple_logic/simpleloop.o

# target to build an object file
server/simple_logic/simpleloop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.o
.PHONY : server/simple_logic/simpleloop.cpp.o

server/simple_logic/simpleloop.i: server/simple_logic/simpleloop.cpp.i
.PHONY : server/simple_logic/simpleloop.i

# target to preprocess a source file
server/simple_logic/simpleloop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.i
.PHONY : server/simple_logic/simpleloop.cpp.i

server/simple_logic/simpleloop.s: server/simple_logic/simpleloop.cpp.s
.PHONY : server/simple_logic/simpleloop.s

# target to generate assembly for a file
server/simple_logic/simpleloop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simpleloop.cpp.s
.PHONY : server/simple_logic/simpleloop.cpp.s

server/simple_logic/simplequeue.o: server/simple_logic/simplequeue.cpp.o
.PHONY : server/simple_logic/simplequeue.o

# target to build an object file
server/simple_logic/simplequeue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.o
.PHONY : server/simple_logic/simplequeue.cpp.o

server/simple_logic/simplequeue.i: server/simple_logic/simplequeue.cpp.i
.PHONY : server/simple_logic/simplequeue.i

# target to preprocess a source file
server/simple_logic/simplequeue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.i
.PHONY : server/simple_logic/simplequeue.cpp.i

server/simple_logic/simplequeue.s: server/simple_logic/simplequeue.cpp.s
.PHONY : server/simple_logic/simplequeue.s

# target to generate assembly for a file
server/simple_logic/simplequeue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplequeue.cpp.s
.PHONY : server/simple_logic/simplequeue.cpp.s

server/simple_logic/simplereward.o: server/simple_logic/simplereward.cpp.o
.PHONY : server/simple_logic/simplereward.o

# target to build an object file
server/simple_logic/simplereward.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.o
.PHONY : server/simple_logic/simplereward.cpp.o

server/simple_logic/simplereward.i: server/simple_logic/simplereward.cpp.i
.PHONY : server/simple_logic/simplereward.i

# target to preprocess a source file
server/simple_logic/simplereward.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.i
.PHONY : server/simple_logic/simplereward.cpp.i

server/simple_logic/simplereward.s: server/simple_logic/simplereward.cpp.s
.PHONY : server/simple_logic/simplereward.s

# target to generate assembly for a file
server/simple_logic/simplereward.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplereward.cpp.s
.PHONY : server/simple_logic/simplereward.cpp.s

server/simple_logic/simplestate.o: server/simple_logic/simplestate.cpp.o
.PHONY : server/simple_logic/simplestate.o

# target to build an object file
server/simple_logic/simplestate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.o
.PHONY : server/simple_logic/simplestate.cpp.o

server/simple_logic/simplestate.i: server/simple_logic/simplestate.cpp.i
.PHONY : server/simple_logic/simplestate.i

# target to preprocess a source file
server/simple_logic/simplestate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.i
.PHONY : server/simple_logic/simplestate.cpp.i

server/simple_logic/simplestate.s: server/simple_logic/simplestate.cpp.s
.PHONY : server/simple_logic/simplestate.s

# target to generate assembly for a file
server/simple_logic/simplestate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/simple_logic/simplestate.cpp.s
.PHONY : server/simple_logic/simplestate.cpp.s

tests/testbaseprotocol.o: tests/testbaseprotocol.cpp.o
.PHONY : tests/testbaseprotocol.o

# target to build an object file
tests/testbaseprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testbaseprotocol.cpp.o
.PHONY : tests/testbaseprotocol.cpp.o

tests/testbaseprotocol.i: tests/testbaseprotocol.cpp.i
.PHONY : tests/testbaseprotocol.i

# target to preprocess a source file
tests/testbaseprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testbaseprotocol.cpp.i
.PHONY : tests/testbaseprotocol.cpp.i

tests/testbaseprotocol.s: tests/testbaseprotocol.cpp.s
.PHONY : tests/testbaseprotocol.s

# target to generate assembly for a file
tests/testbaseprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testbaseprotocol.cpp.s
.PHONY : tests/testbaseprotocol.cpp.s

tests/testclientprotocol.o: tests/testclientprotocol.cpp.o
.PHONY : tests/testclientprotocol.o

# target to build an object file
tests/testclientprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testclientprotocol.cpp.o
.PHONY : tests/testclientprotocol.cpp.o

tests/testclientprotocol.i: tests/testclientprotocol.cpp.i
.PHONY : tests/testclientprotocol.i

# target to preprocess a source file
tests/testclientprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testclientprotocol.cpp.i
.PHONY : tests/testclientprotocol.cpp.i

tests/testclientprotocol.s: tests/testclientprotocol.cpp.s
.PHONY : tests/testclientprotocol.s

# target to generate assembly for a file
tests/testclientprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testclientprotocol.cpp.s
.PHONY : tests/testclientprotocol.cpp.s

tests/testserverprotocol.o: tests/testserverprotocol.cpp.o
.PHONY : tests/testserverprotocol.o

# target to build an object file
tests/testserverprotocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testserverprotocol.cpp.o
.PHONY : tests/testserverprotocol.cpp.o

tests/testserverprotocol.i: tests/testserverprotocol.cpp.i
.PHONY : tests/testserverprotocol.i

# target to preprocess a source file
tests/testserverprotocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testserverprotocol.cpp.i
.PHONY : tests/testserverprotocol.cpp.i

tests/testserverprotocol.s: tests/testserverprotocol.cpp.s
.PHONY : tests/testserverprotocol.s

# target to generate assembly for a file
tests/testserverprotocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_tests.dir/build.make CMakeFiles/taller_tests.dir/tests/testserverprotocol.cpp.s
.PHONY : tests/testserverprotocol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... SDL2pp"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... taller_client"
	@echo "... taller_common"
	@echo "... taller_editor"
	@echo "... taller_server"
	@echo "... taller_tests"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... common/clientprotocol.o"
	@echo "... common/clientprotocol.i"
	@echo "... common/clientprotocol.s"
	@echo "... common/core/liberror.o"
	@echo "... common/core/liberror.i"
	@echo "... common/core/liberror.s"
	@echo "... common/core/protocol.o"
	@echo "... common/core/protocol.i"
	@echo "... common/core/protocol.s"
	@echo "... common/core/resolver.o"
	@echo "... common/core/resolver.i"
	@echo "... common/core/resolver.s"
	@echo "... common/core/resolvererror.o"
	@echo "... common/core/resolvererror.i"
	@echo "... common/core/resolvererror.s"
	@echo "... common/core/socket.o"
	@echo "... common/core/socket.i"
	@echo "... common/core/socket.s"
	@echo "... common/protocolerror.o"
	@echo "... common/protocolerror.i"
	@echo "... common/protocolerror.s"
	@echo "... common/serverprotocol.o"
	@echo "... common/serverprotocol.i"
	@echo "... common/serverprotocol.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... server/controlledplayer.o"
	@echo "... server/controlledplayer.i"
	@echo "... server/controlledplayer.s"
	@echo "... server/controlnotifier.o"
	@echo "... server/controlnotifier.i"
	@echo "... server/controlnotifier.s"
	@echo "... server/controlreceiver.o"
	@echo "... server/controlreceiver.i"
	@echo "... server/controlreceiver.s"
	@echo "... server/gameerror.o"
	@echo "... server/gameerror.i"
	@echo "... server/gameerror.s"
	@echo "... server/lobbycontainer.o"
	@echo "... server/lobbycontainer.i"
	@echo "... server/lobbycontainer.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
	@echo "... server/match.o"
	@echo "... server/match.i"
	@echo "... server/match.s"
	@echo "... server/playeracceptor.o"
	@echo "... server/playeracceptor.i"
	@echo "... server/playeracceptor.s"
	@echo "... server/playercontainer.o"
	@echo "... server/playercontainer.i"
	@echo "... server/playercontainer.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... server/simple_logic/simpleaction.o"
	@echo "... server/simple_logic/simpleaction.i"
	@echo "... server/simple_logic/simpleaction.s"
	@echo "... server/simple_logic/simplebox.o"
	@echo "... server/simple_logic/simplebox.i"
	@echo "... server/simple_logic/simplebox.s"
	@echo "... server/simple_logic/simpleloop.o"
	@echo "... server/simple_logic/simpleloop.i"
	@echo "... server/simple_logic/simpleloop.s"
	@echo "... server/simple_logic/simplequeue.o"
	@echo "... server/simple_logic/simplequeue.i"
	@echo "... server/simple_logic/simplequeue.s"
	@echo "... server/simple_logic/simplereward.o"
	@echo "... server/simple_logic/simplereward.i"
	@echo "... server/simple_logic/simplereward.s"
	@echo "... server/simple_logic/simplestate.o"
	@echo "... server/simple_logic/simplestate.i"
	@echo "... server/simple_logic/simplestate.s"
	@echo "... tests/testbaseprotocol.o"
	@echo "... tests/testbaseprotocol.i"
	@echo "... tests/testbaseprotocol.s"
	@echo "... tests/testclientprotocol.o"
	@echo "... tests/testclientprotocol.i"
	@echo "... tests/testclientprotocol.s"
	@echo "... tests/testserverprotocol.o"
	@echo "... tests/testserverprotocol.i"
	@echo "... tests/testserverprotocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

